### ISSUE TITLE
Generics code generation error

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [square/dagger#457] opened 2015-01-19 01:44 UTC
Hi.
Not sure if it's worthy to have a raised issue here (duplicate, off-topic, etc), but let me try. I'm trying to create generic modules, but the codegen produces unexpected output that's does not let me proceed further. Suppose I have the following module:

    @Module....
    public final class FeedActivityModule<FID, PID> {

When I'm building the application using Maven, I'm getting the following error:

    .../app-android/target/generated-sources/annotations/.../activities/feed/FeedActivityModule$$ModuleAdapter.java:[64,188] <identifier> expected

This is probably the reason of the error coming from the generated file:

    ... linker.requestBinding("...", FeedActivityModule<FID, PID>.class, getClass().getClassLoader())

that's a Java syntax error (take a look at the `<FID, PID>.class` string). Am I just missing something important or you confirm it's a bug?

Thanks.

**Comment by JakeWharton** [comment] 2015-01-19 02:31
This is a dupe of #396. I'll say that this is highly unlikely to happen with Dagger 1.

**Closed by JakeWharton** 2015-01-19 02:31 UTC

**Comment by lyubomyr-shaydariv** [comment] 2015-01-19 07:58
Oops, sorry for the dupe.
